import { makeStyles } from "@material-ui/core";

const CompanyStyle = makeStyles((theme)=>({
    container:{
        display:'flex',
        flexDirection:'column'
    },
    grow:{
        flexGrow:1
    },
    formContainer:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
    },
    form:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        width:'50%'
    },
    formInfo:{
        marginBottom:20
    },
    text_input:{
        width:'100%',
        marginBottom:50
    },
    text_area:{
        width:'100%',
        padding:10,
        marginBottom:50
    },
    birthDate:{
        display:"flex",
        flexDirection:'column',
        alignItems:'flex-start',
        width:'100%',
        marginBottom:30
    },
    genderInnerLayout:{
        display:"flex",
        flexDirection:'row'
    },
    upload:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center',
        marginBottom:25
    },
    contactContainer:{
        display:'flex',
        flexDirection:'column',
        width:'100%'
    },
    welcome:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center'
    },
    company_logo:{
        display:'flex',
        flexDirection:'column',
        marginBottom:20
    },
    noStock:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center'
    },
    noLoan:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center'
    },
    info:{
       marginBottom:20
    }
}))

export default CompanyStyle